build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: true

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '4'
      - '8'
      - '16'
      - '24'
      - '32'
      - '48'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
  WildcardImport:
    active: true

complexity:
  LongMethod:
    active: true
    threshold: 40
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 15

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - 'Composable'
  MatchingDeclarationName:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: true
  TooGenericExceptionThrown:
    active: true
